version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports: 
      - 27017:27017
    networks:
      - mongodb_network
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    ports:
      - 3002:8081
    networks:
      - mongodb_network
    restart: always
  app1:
    depends_on:
      - mongo-express
    build: ./app1
    ports: 
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1 ## We want this to work with docker stack?
  app2:
    depends_on:
      - app1
    build: ./app2
    ports: 
      - 3001:3000

volumes: 
  mongodb_data:

networks:
  mongodb_network: