version: "3.9"
services: 
  app1:
    build: ./app1
    ports: 
      - 3000:3000
    volumes:
      - sharedvolume:/usr/src/app:ro
  app2:
    build: ./app2
    ports: 
      - 3001:3000
    volumes_from: 
      - app1

volumes: 
  sharedvolume: