version: "3.9"
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - viking-network
    volumes:
      - mongodb_data:/data/db
    env_file: 
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    ports:
      - 3002:8081
    networks:
      - viking-network
    restart: always
    env_file:
      - .env
  app1:
    depends_on:
      - mongo
    build: ./app1
    image: app1
    ports: 
      - 3000:3000
    networks:
      - viking-network
    restart: always
    volumes:
      # Mount host source code into container
      - ./app1/:/usr/src/app
      # The following stops the container from syncing back to host
      - /usr/src/app/node_modules
    env_file: 
      - .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      # We just set "mongo" here, this will point to the docker service "mongo" we have earlier in this document.
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    command: npm start
  app2:
    depends_on:
      - app1
    build: ./app2
    image: app2
    ports: 
      - 3001:3000

volumes:
  mongodb_data:

networks:
  viking-network: